config/routes.rb
Mathhotspot::Application.routes.draw do

  devise_for :users

  root :to => "Worksheets::MyWorksheets#index"
  
  resources :categories
  
  resource :instructions

  match 'admin' => 'admin#index', :as => :admin

  namespace :admin do
    resources :subjects, :except => [:show]
    resources :lessons, :except => [:show]
  end  
    
  resources :tags, :except => [:index, :new, :create, :edit, :update, :show, :delete]
  
  resources :subjects, :only => [:show, :index]
    
  resources :lessons

  resources :math_problems, :except => [:new, :index]
  
  get "my_worksheets" => 'worksheets/my_worksheets#index', :as => :my_worksheets
  
  get "math_problems/:math_problem_id/new" => 'clone/math_problem_clone#new', :as => :math_problem_clone
  get "worksheets/:worksheet_id/problem/:problem_number/new" => 'clone/worksheet_problem_clone#new', 
    :as => :worksheet_problem_clone

  resources :worksheets do
    resources :worksheet_problems, :only => [:update, :new]
  end

  resources :worksheet_problems, :only => [:destroy, :create]
  
  post "worksheet_problem_replacer" => 'worksheet_problem_replacer#create', :as => :worksheet_problem_replacer
  post "worksheet_problem_adder" => 'worksheet_problem_adder#create', :as => :worksheet_problem_adder
  
  resources :worksheet_solutions, :only => [:show]
  
  match "problem_types/search/results" => 'problem_types/search#show', :as => :problem_types_search
  match "problem_types/search" => 'problem_types/search#new', :as => :new_problem_types_search

  post "worksheet_builder" => 'worksheet_builder#create', :as => :worksheet_builder
  get "problem_types/:permalink/worksheet_builder" => 'problem_type_worksheet_builder#new',
    :as => :new_problem_type_worksheet_builder
  get "lessons/:id/worksheet_builder" => 'lesson_worksheet_builder#new', :as => :new_lesson_worksheet_builder

  resources :problem_types, :except => [:delete] do
    resources :problem_levels, :except => [:create] do
      resources :math_problems, :only => [:new]
    end
    resources :available_tags, :only => [:index]
  end
    
  resources :problem_levels, :only => [:create]
  
  resources :core_lesson_problem_types, :only => [:create]
    
  match '/dashboard' => 'dashboards#show', :as => :dashboard
  match '/my_lessons' => 'my_lessons#index', :as => :my_lessons
  match '/problem_types/:problem_type_id/available_tags/search' => 'available_tags#search', :as => :available_tag_search
  

end

app/controllers/worksheet_solutions_controller.rb
class WorksheetSolutionsController < ApplicationController
  def show
    @worksheet = Worksheet.find(params[:id])
  end
end

app/helpers/worksheet_solutions_helper.rb
module WorksheetSolutionsHelper
end

app/views/worksheet_solutions/_worksheet_problem_solution.html.haml
.worksheet-problem{:id => "problem_#{worksheet_problem.problem_number}"}
  %span.problem_number
    =display_problem_number(worksheet_problem)
  = render :partial => "math_problems/problem_display", :locals => { :math_problem => worksheet_problem.math_problem, :should_show_solution => true }

app/views/worksheet_solutions/show.html.haml
- content_for :head do
  %title
    ="Worksheet #{@worksheet.id} Solutions"

.worksheet{:id => "worksheet_#{@worksheet.id}"}
  #worksheet_links
    = link_to "Hide Solutions", worksheet_path(@worksheet)
    |
    = link_to "Edit Worksheet", edit_worksheet_path(@worksheet)

  #worksheet-title
    =@worksheet.title

  #worksheet-problems
    -@worksheet.problem_groups.each do |group|
      .problem_group
        .instructions
          = group.first.instruction.description
        -group.each do |worksheet_problem|
          = render :partial => "worksheet_solutions/worksheet_problem_solution", :locals => { :worksheet_problem => worksheet_problem }