config/routes.rb
Mathhotspot::Application.routes.draw do

  devise_for :users

  root :to => "Worksheets::MyWorksheets#index"
  
  resources :categories
  
  resource :instructions

  match 'admin' => 'admin#index', :as => :admin

  namespace :admin do
    resources :subjects, :except => [:show]
    resources :lessons, :except => [:show]
  end  
    
  resources :tags, :except => [:index, :new, :create, :edit, :update, :show, :delete]
  
  resources :subjects, :only => [:show, :index]
    
  resources :lessons

  resources :math_problems, :except => [:new, :index]
  
  get "my_worksheets" => 'worksheets/my_worksheets#index', :as => :my_worksheets
  
  get "math_problems/:math_problem_id/new" => 'clone/math_problem_clone#new', :as => :math_problem_clone
  get "worksheets/:worksheet_id/problem/:problem_number/new" => 'clone/worksheet_problem_clone#new', 
    :as => :worksheet_problem_clone

  resources :worksheets do
    resources :worksheet_problems, :only => [:update, :new]
  end

  resources :worksheet_problems, :only => [:destroy, :create]
  
  post "worksheet_problem_replacer" => 'worksheet_problem_replacer#create', :as => :worksheet_problem_replacer
  post "worksheet_problem_adder" => 'worksheet_problem_adder#create', :as => :worksheet_problem_adder
  
  resources :worksheet_solutions, :only => [:show]
  
  match "problem_types/search/results" => 'problem_types/search#show', :as => :problem_types_search
  match "problem_types/search" => 'problem_types/search#new', :as => :new_problem_types_search

  post "worksheet_builder" => 'worksheet_builder#create', :as => :worksheet_builder
  get "problem_types/:permalink/worksheet_builder" => 'problem_type_worksheet_builder#new',
    :as => :new_problem_type_worksheet_builder
  get "lessons/:id/worksheet_builder" => 'lesson_worksheet_builder#new', :as => :new_lesson_worksheet_builder

  resources :problem_types, :except => [:delete] do
    resources :problem_levels, :except => [:create] do
      resources :math_problems, :only => [:new]
    end
    resources :available_tags, :only => [:index]
  end
    
  resources :problem_levels, :only => [:create]
  
  resources :core_lesson_problem_types, :only => [:create]
    
  match '/dashboard' => 'dashboards#show', :as => :dashboard
  match '/my_lessons' => 'my_lessons#index', :as => :my_lessons
  match '/problem_types/:problem_type_id/available_tags/search' => 'available_tags#search', :as => :available_tag_search
  

end

app/models/math_problem.rb
class MathProblem < ActiveRecord::Base
  include MathHotSpotErrors
  include RightRabbitErrors
  
  has_many :worksheet_problems, :dependent => :destroy
  has_many :worksheets, :through => :worksheet_problems
  belongs_to :problem_level
  has_one :problem_type, :through => :problem_level
  belongs_to :owner, :class_name => "User"

  validates_presence_of :question_markup, :answer_markup, :owner_id
  validates :question_markup, :uniqueness => {:scope => :problem_level_id}
  validate :problem_level_exists_if_specified, :owner_exists

  before_validation :strip_excess_tags, :replace_xmlns_with_display_block
  
  
  DEFAULT_INSTRUCTION = Instruction.new(:description => MathHotSpotErrors::Message::NO_INSTRUCTIONS)
      
  def self.group_by_problem_level
    groups = []
    MathProblem.all.chunk {|problem| problem.problem_level }.each {|level, group| groups << group }
    groups
  end
    
  def display_mode?
    problem_level.nil? ? true : problem_level.display_mode?
  end
  
  def instruction
    problem_level.nil? ? DEFAULT_INSTRUCTION : problem_level.instruction
  end

  def instruction_description
    instruction.description
  end
  
  def siblings(max_count = nil)
    all_siblings = problem_level.nil? ? [] : problem_level.math_problems.reject {|current| current == self}
    requested_sibs = max_count == nil ? all_siblings : all_siblings.first(max_count)
  end
  
  def sibling_available?(options = {})
    begin
      available_problems = find_problem_from_same_level options
      true
    rescue
      false
    end
  end
  
  def find_problem_from_same_level(options = {})
    available_problems = MathProblem.find_all_by_problem_level_id(self.problem_level.id)

    if available_problems.empty?
      raise ActiveRecord::RecordNotFound
    end
    
    # then problem is irreplaceable -- it's one of a kind
    raise UniqueProblemError if (available_problems.count == 1)
  
    if options[:exclude]
      available_problems.reject! {|problem| options[:exclude].include? problem }
    end
        
    without_original = available_problems.delete_if {|problem| problem == self}
    
    if without_original.empty?
      raise NoSimilarProblemsRemainingError
    end
    
    without_original[rand(without_original.size)]
  end
  
  def classified?
    !problem_level.nil?
  end
  
  private

  def owner_exists
    if owner_id
      errors.add(:owner_id, "doesn't exist in database") unless User.exists?(owner_id)
    end
  end
  
  def problem_level_exists_if_specified
    errors.add(:problem_level_id, "not found in db") unless (problem_level_id.nil? || problem_level || (problem_level_id && ProblemLevel.exists?(problem_level_id)))
  end
  
  def strip_excess_tags
    [question_markup, answer_markup].each do |markup|
      unless markup.nil?
        markup.gsub!(/\n/,"")
        markup.gsub!(/<\/?semantics>|<annotation.*annotation>/,"")
        markup.gsub!(/>\s*</,"><")
        markup.strip!
      end
    end
  end
  
  def replace_xmlns_with_display_block
    if question_markup 
      question_markup.gsub!(/xmlns='.+?'/,"display='block'")
    end
    if answer_markup
      answer_markup.gsub!(/xmlns='.+?'/,"display='block'")
    end
  end
     
end

app/controllers/math_problems_controller.rb
class MathProblemsController < ApplicationController  
  def show
    @math_problem = MathProblem.find(params[:id])
  end
  
  def create
    @math_problem = MathProblem.new(params[:math_problem].merge({:owner => current_user }))
    respond_to do |format|
      if @math_problem.save
        format.html { redirect_to(@math_problem, :notice => 'Math Problem was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  
  def new
    @problem_type = ProblemType.find_by_permalink(params[:problem_type_id])
    problem_level = ProblemLevel.find_by_level_number_and_problem_type_id(params[:problem_level_id], @problem_type.id)
    @math_problem = MathProblem.new(:problem_level => problem_level)
    @siblings = @math_problem.siblings(10)
  end

  def edit
    @math_problem = MathProblem.find(params[:id])
    @problem_type = @math_problem.problem_type
  end
  
  def update
    @math_problem = MathProblem.find(params[:id])
    if @math_problem.update_attributes(params[:math_problem])
      redirect_to(@math_problem, :notice => 'Math problem successfully updated')
    else
      render :action => 'edit'
    end
  end

  def destroy
    @math_problem = MathProblem.find(params[:id])
    @math_problem.destroy
    redirect_to root_url 
  end    
end

app/helpers/math_problems_helper.rb
module MathProblemsHelper
  
  def display_mathml_question(math_problem)
    display_mathml(math_problem, true)
  end

  def display_mathml_answer(math_problem)
    display_mathml(math_problem, false)
  end
  
  def display_mathml(problem, display_question = true)
    unless problem
      MathHotSpotErrors::Message::NO_SAMPLE_MATH_PROBLEM_FOUND
    else
      markup = display_question ? problem.question_markup : problem.answer_markup
      text = display_question ? "question" : "answer"
      unless markup.nil?
        start_tag, end_tag = "<p class='inline_math'>","</p>"
        problem.display_mode? ? markup.html_safe : start_tag.concat(markup).concat(end_tag).html_safe
      else
        "No #{text} specified."
      end
    end
  end
  
  def display_solution(problem)
    display_mathml(problem, false)
  end
    
  def problem_type_count_msg(count)
    count > 1 ? "(#{count} problem types)" : "(1 problem type)"
  end

  def sibling_count(siblings, total_count)
    if (total_count == siblings)
      last_word = siblings == 1 ? "problem" : "problems"
      "(#{total_count} #{last_word})"
    else
      "(#{siblings} of #{total_count} problems)"
    end
  end
  
  def add_to_current_worksheet_link_if_applicable(math_problem)
    if current_worksheet?
      begin
        current_worksheet = Worksheet.find(session[:current_worksheet_id])
        unless current_worksheet.math_problems.include? math_problem
          render(:partial => "math_problems/add_math_problem_to_current_worksheet", :locals => {:worksheet_problem => WorksheetProblem.new(:math_problem => math_problem, :worksheet => current_worksheet, :problem_number => current_worksheet.next_available_problem_number)})
        end
      rescue ActiveRecord::RecordNotFound
        clear_current_worksheet_in_session!
      end
    end
  end  
end

app/views/math_problems/_add_math_problem_to_current_worksheet.html.haml
= simple_form_for(worksheet_problem) do |form|
  = form.input :worksheet_id, :as => :hidden
  = form.input :math_problem_id, :as => :hidden
  = form.submit "Add Problem to Worksheet"

app/views/math_problems/_current_level_display.html.haml
#current-level-display
  %h4
    Some Existing Problems
    = sibling_count(siblings.count, math_problem.siblings.count)
  #instructions
    = math_problem.instruction_description
  #sibling-problems
    - siblings.each do |sibling_problem|
      .math-display
        .problem_display
          =display_mathml_question(sibling_problem)
  #links
    =link_to 'Menu', root_url

app/views/math_problems/_form.html.haml
= simple_form_for(math_problem) do |f|
  - if math_problem.errors.any?
    .error_explanation
      %h2
        = pluralize(math_problem.errors.count, "error")
      %ul
        - math_problem.errors.full_messages.each do |msg|
          %li
            = msg
  = f.association :problem_level, :as => :hidden
  = render :partial => 'math_problems/question_and_answer_markup', :locals => { :form => f }
  
  #level
    = f.association :problem_level, :label => "Level: ", :collection => @problem_type.problem_levels, :label_method => :level_number, :include_blank => false, :confirm => "Are you sure?"

  .actions
    = f.submit
  

app/views/math_problems/_form_contents.html.haml
= form.association :problem_level, :as => :hidden
#math-markup-input-fields
  #question
    #question-equation-editor
      =link_to "Launch Equation Editor for Question", "javascript:OpenLatexEditor('math_problem_question_markup','latex','')"
    .editor-explanation
      (note: will add to existing markup)
    #question_markup
      = form.input :question_markup, :as => :text
  #answer
    #answer-equation-editor
      =link_to "Launch Equation Editor for Answer", "javascript:OpenLatexEditor('math_problem_answer_markup','latex','')"
    .editor-explanation
      (note: will add to existing markup)
    #answer_markup
      = form.input :answer_markup, :as => :text 
#level
  = form.association :problem_level, :label => "Level: ", :collection => @problem_type.problem_levels, :label_method => :level_number, :include_blank => false, :confirm => "Are you sure?"
      
.actions
  = form.submit

app/views/math_problems/_grouped.html.haml
.problem_collection
  %h2 Grouped Math Problems
  - problem_groups.each do |group|
    .index_group_container_odd
      .problem_instruction 
        = group.first.instruction.description
      - group.each do |problem|
        .problem
          = render(:partial => "problem_display", :locals => { :math_problem => problem })

app/views/math_problems/_math_problem.html.erb
<div class="worksheet_problem" id="problem_<%= problem_number %>">
	<span class="problem_number"><%= problem_number %>)</span>
	<%= render :partial => "math_problems/problem_display", :locals => { :math_problem => math_problem} %>
	<div class="problem_links">
	  <%= form_tag(worksheet_path(worksheet), :method => 'put', :class => "replace_problem_form", :id => "replace_problem_form_#{problem_number}") do -%>
	  <input type="hidden" name="problem_number" value="<%= problem_number %>" />
    <input id="replace_problem_submit_<%= problem_number %>" class="replace_problem_submit" 
	    type="submit" value="replace" />
    <% end -%>
		</div>
		<div class="error_display"></div>
</div>

app/views/math_problems/_math_problem_full.html.haml
.math-display
  .math-problem
    .math-problem-full
      .question_and_answer
        Question:
        =display_mathml_question(math_problem)
        Answer:
        =display_mathml_answer(math_problem)
  .math-problem-links
    =link_to 'Edit Problem', edit_math_problem_url(math_problem)
    %br
    =link_to 'Create Similar Problem', math_problem_clone_url(math_problem)
    %br
    = add_to_current_worksheet_link_if_applicable(math_problem)
  

app/views/math_problems/_nested_problem_form.html.haml
.new_problem_form
  =builder.fields_for :math_problems do |problem_builder|
    =render :partial => 'math_problems/question_and_answer_markup', :locals => { :form => problem_builder }

app/views/math_problems/_problem_display.html.haml
.math-display
  .question
    = display_mathml_question(math_problem)
  - if should_show_solution
    .answer
      Solution:
      = display_solution(math_problem)

app/views/math_problems/grouped.html.haml
- content_for :head do
  %title Grouped Math Problems
  = stylesheet_link_tag "admin/math_problems"

= render(:partial => "grouped", :locals => {:problem_groups => @problem_groups})

app/views/math_problems/index.html.haml
- content_for :head do
  %title Math Problems
  = stylesheet_link_tag "admin/math_problems"

#container
  #subject_list
    %h2 Search by Subject
    - @subjects.each do |subject|
      .subject
        = subject.title
        = render :partial => "categories/index_with_lessons", :locals => {:subject => subject}
  #tag_section
    %h2 Search by Tags
    #tag_list
      - @tags.each do |tag|
        %span.tag
          =tag.name

app/views/math_problems/index.xhtml.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "admin/math_problems" %>
<% end %>

<div id="container">
  <% @math_problems.each do |problem| %>
    <div class="problem">
      <div class="problem_id"><%= problem.id %></div>
      <%= render :partial => "problem_display.xhtml.erb", :locals => { :math_problem => problem } %>
    </div>
  <% end %>
</div>

app/views/math_problems/new.html.haml
- content_for :head do
  %title New Math Problem
  = stylesheet_link_tag "math_display", "problem_entry_form"
  = javascript_include_tag latex_generator_popup_url
  
#new-math-problem
  .page-title New Math Problem
  =render :partial => 'math_problems/form', :locals => { :math_problem => @math_problem }
  
= render :partial => 'math_problems/current_level_display', :locals => { :siblings => @siblings, :math_problem => @math_problem }

app/views/math_problems/rogue.html.haml
- content_for :head do
  %title Rougue Math Problems
  = stylesheet_link_tag "admin/math_problems"

= render(:partial => 'rogue', :locals => {:rogues => @rogue_problems})