config/routes.rb
Mathhotspot::Application.routes.draw do

  devise_for :users

  root :to => "Worksheets::MyWorksheets#index"
  
  resources :categories
  
  resource :instructions

  match 'admin' => 'admin#index', :as => :admin

  namespace :admin do
    resources :subjects, :except => [:show]
    resources :lessons, :except => [:show]
  end  
    
  resources :tags, :except => [:index, :new, :create, :edit, :update, :show, :delete]
  
  resources :subjects, :only => [:show, :index]
    
  resources :lessons

  resources :math_problems, :except => [:new, :index]
  
  get "my_worksheets" => 'worksheets/my_worksheets#index', :as => :my_worksheets
  
  get "math_problems/:math_problem_id/new" => 'clone/math_problem_clone#new', :as => :math_problem_clone
  get "worksheets/:worksheet_id/problem/:problem_number/new" => 'clone/worksheet_problem_clone#new', 
    :as => :worksheet_problem_clone

  resources :worksheets do
    resources :worksheet_problems, :only => [:update, :new]
  end

  resources :worksheet_problems, :only => [:destroy, :create]
  
  post "worksheet_problem_replacer" => 'worksheet_problem_replacer#create', :as => :worksheet_problem_replacer
  post "worksheet_problem_adder" => 'worksheet_problem_adder#create', :as => :worksheet_problem_adder
  
  resources :worksheet_solutions, :only => [:show]
  
  match "problem_types/search/results" => 'problem_types/search#show', :as => :problem_types_search
  match "problem_types/search" => 'problem_types/search#new', :as => :new_problem_types_search

  post "worksheet_builder" => 'worksheet_builder#create', :as => :worksheet_builder
  get "problem_types/:permalink/worksheet_builder" => 'problem_type_worksheet_builder#new',
    :as => :new_problem_type_worksheet_builder
  get "lessons/:id/worksheet_builder" => 'lesson_worksheet_builder#new', :as => :new_lesson_worksheet_builder

  resources :problem_types, :except => [:delete] do
    resources :problem_levels, :except => [:create] do
      resources :math_problems, :only => [:new]
    end
    resources :available_tags, :only => [:index]
  end
    
  resources :problem_levels, :only => [:create]
  
  resources :core_lesson_problem_types, :only => [:create]
    
  match '/dashboard' => 'dashboards#show', :as => :dashboard
  match '/my_lessons' => 'my_lessons#index', :as => :my_lessons
  match '/problem_types/:problem_type_id/available_tags/search' => 'available_tags#search', :as => :available_tag_search
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  include Topicable
  
  belongs_to :subject
  has_many :problem_types
  has_many :lessons

  validates_presence_of :title
  
  before_destroy :empty?
  
  def empty?
    problem_types.empty?
  end
  
  def name
    subject.nil? ? title : "#{subject.title} -- #{title}"
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :subject %><br />
    <%= f.select(:subject_id, Subject.all.collect {|subject| [subject.title, subject.id]}) %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_index_with_lessons.html.haml
%ul.category_list
  - subject.categories.each do |category|
    %li
      ="#{category.title}"
      %ul.lesson_list
        - category.lessons.each do |lesson|
          %li
            =link_to lesson.title, lesson_path(lesson)
            =problem_type_count(lesson)

app/views/categories/_index_with_problem_types.html.haml
%ul.category_list
  - categories.each do |category|
    %li
      ="#{category.title}"
      %ul.problem_type_list
        - category.problem_types.each do |problem_type|
          %li
            =link_to problem_type.title, problem_type_path(problem_type)
            =problem_count_msg(problem_type)

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Subject</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.title %></td>
    <td><%= category.subject_id %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= link_to "Create new Subject", new_admin_subject_url %>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Subject:</b>
  <%= @category.subject_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>